/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pkg_MyClass */

#ifndef _Included_pkg_MyClass
#define _Included_pkg_MyClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pkg_MyClass
 * Method:    ptr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_pkg_MyClass_ptr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
